#!/bin/bash
ICON_PLAY=""
ICON_PAUSE=""
CUR_ICON=""
PLAYER_STATUS=$(cmus-remote -Q | grep 'status' | cut -d ' ' -f2-)
variable=$(basename -az $(cmus-remote -Q | grep file | cut -d ' ' -f2-)

if [[ "${PLAYER_STATUS}" = "paused" ]]; then
  CUR_ICON="${ICON_PAUSE}"
  echo " ${CUR_ICON} ${INFO_TITLE= $(basename -az $(cmus-remote -Q | grep file | cut -d ' ' -f2-))}"
elif [[ "${PLAYER_STATUS}" = "playing" ]]; then
  CUR_ICON="${ICON_PLAY}"
  echo " ${CUR_ICON} ${INFO_TITLE= $(basename -az $(cmus-remote -Q | grep file | cut -d ' ' -f2-))}"
else
#  CUR_ICON="${ICON_STOP}"
  echo ""
fi

case $BLOCK_BUTTON in
  1) cmus-remote -c -u ;; 
  2) cmus-remote -c -s ;;
  3) cmus-remote -c -n ;;

esac
